Contributing security updates for httpd
eclipse-che/che-devfile-registry pull request #459
Opened 2021-07-30 12:59 UTC by ArvinB

This will deny access to security sensitive .ht files and increase the default encryption level for SSL.

### What does this PR do?

### Screenshot/screencast of this PR

### What issues does this PR fix or reference?

https://issues.redhat.com/browse/CRW-2118

### How to test this PR?

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [X] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [X] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [X] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [X] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [X] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [X] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [X] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [X] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [X] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

We use these settings downstream in IBM Wazi Developer for Workspaces.

2021-07-30 13:00 UTC, ArvinB commented
@nickboldt @ericwill FYI
I only updated the rhel.dockerfile because the other one was more generic using alpine httpd.

2021-07-30 14:34 UTC, nickboldt approved these changes

2021-07-30 14:43 UTC, benoitf requested changes
please look at the comments there (for plugin registry)
https://github.com/eclipse-che/che-plugin-registry/pull/1014/files

2021-09-22 06:34 UTC, svor approved these changes

2021-09-22 06:40 UTC, benoitf approved these changes

2021-09-22 08:24 UTC, merged